Task/authentication flow
zrock-dev/antwood pull request #14
Opened 2023-11-13 20:15 UTC by daniel-espinoza-79

This Pull Request focuses on bolstering the application's frontend by seamlessly incorporating user registration and login functionality. We've introduced intuitive UI elements and client-side logic to enable users to create accounts and sign in conveniently, while ensuring secure data transmission to the backend. These enhancements are set to improve the overall user experience and strengthen the application's security measures.

2023-11-13 23:51 UTC, zrock-dev requested changes

2023-11-13 23:51 UTC, zrock-dev commented on backend/account_management/context/controllers/AuthController.go
> +	claims, authError := service.GetAppClaims(authTocken)
You have a typo in the word authTocken

2023-11-13 23:51 UTC, zrock-dev commented on frontend/src/requests/AuthRequest.js
> +  axios.get(`${AUTH_DOMAIN}/auth/logout`, axiosConfig);
In what cases will the backend tell you that the user has logged out?

2023-11-14 07:46 UTC, daniel-espinoza-79 commented on backend/account_management/context/controllers/AuthController.go
> +	claims, authError := service.GetAppClaims(authTocken)
done

2023-11-14 08:03 UTC, daniel-espinoza-79 commented on frontend/src/requests/AuthRequest.js
> +  axios.get(`${AUTH_DOMAIN}/auth/logout`, axiosConfig);
It is actually a post request covered in a get request, because the tokens we manage are Onlyhttp, that is, we cannot manage them with js, and to access them they are done through get,and if the session will be closed correctly the backend will return a 200 as status, otherwise it could be any of the following scenarios:

- When logging out there was no token to decrypt
- the token not generated by our backend
- the token expired
- the token is malformed

2023-11-14 21:35 UTC, zrock-dev approved these changes

2023-11-15 01:12 UTC, JCarlosHidalgoSosa approved these changes

2023-11-15 03:15 UTC, merged