Feature/gallery of items
zrock-dev/antwood pull request #4
Opened 2023-11-07 13:06 UTC by luiggymamani

# Author: Luiggy Mamani Condori

## What did I do?
I implemented the feature to render products with lazy loading using **infinity scrolling**.

## How did I do?
I created a request on the backend to get products from our database **join collections** and send that data with **pagination**

## Why did I do it?
to achieve the goal of our sprint.

2023-11-07 15:19 UTC, VictorCespedesCC approved these changes
Only 1 observation

2023-11-07 15:19 UTC, VictorCespedesCC commented on frontend/src/requests/Requester.js
> +
"localhost:4000" is correct, in other parts of the code it is "localhost:3000".

2023-11-07 17:04 UTC, luiggymamani commented on frontend/src/requests/Requester.js
> +
It is the domain of our server that will run on localhost on port 4000, if you saw a localhost on port 3000, it is where our frontend will run.

I did it so as not to repeat the server's domain several times, but if you saw a request to localhost:3000 you can tell me where it is.

2023-11-08 11:56 UTC, VictorCespedesCC commented on frontend/src/requests/Requester.js
> +
backend/product_management/app/config/Server.go on line 17, but I leave it to your opinion.

2023-11-08 14:48 UTC, luiggymamani commented on frontend/src/requests/Requester.js
> +
It is the configuration of our server's cors so that it is only available for our domain that is on the frontend, which is localhost on port 3000

2023-11-08 18:30 UTC, daniel-espinoza-79 requested changes
the app crashes if a sneaker don't have a color

I know we hope to have sneakers with images but in case there is no image the program should not crash and it increases the security of the application

![Screenshot from 2023-11-08 14-03-07](https://github.com/zrock-dev/antwood/assets/135346738/4e34605e-dbc0-46ea-aadd-2d785bf33290)

2023-11-08 19:51 UTC, luiggymamani commented
> the app crashes if a sneaker don't have a color
> 
> I know we hope to have sneakers with images but in case there is no image the program should not crash and it increases the security of the application
> 
> ![Screenshot from 2023-11-08 14-03-07](https://user-images.githubusercontent.com/135346738/281506079-4e34605e-dbc0-46ea-aadd-2d785bf33290.png)

Solved, I will no render products without colors

2023-11-08 19:55 UTC, daniel-espinoza-79 approved these changes

2023-11-08 19:56 UTC, merged